trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_PROJECTKEY: 'azure-the-test'
  SONAR_PROJECTNAME: 'azure-the-test'

steps:
- checkout: self
  displayName: 'Checkout Source'

- script: |
    docker pull blacklocksec/code-scanner:latest
    docker run --rm -v $(Build.SourcesDirectory):/app \
    -e SONAR_PROJECTKEY='YiBNyFSlxsMr7KsB' \
    -e SONAR_HOST_URL=$(SONAR_HOST_URL) \
    -e SONAR_TOKEN=$(SONAR_TOKEN) \
    blacklocksec/code-scanner:latest
  displayName: 'Run Blacklock Code Scanner'
  env:
    SONAR_HOST_URL: $(SONAR_HOST_URL)
    SONAR_TOKEN: $(SONAR_TOKEN)
  fetchDepth: 0
