trigger:
- master

pool:
  vmImage: 'maven:3-eclipse-temurin-17'

variables:
  SONAR_PROJECTKEY: 'azure-the-test'
  SONAR_PROJECTNAME: 'azure-the-test'

steps:
- checkout: self
  displayName: 'Checkout Source'

- task: Cache@2
  inputs:
    key: 'sonar | $(Agent.OS)'
    path: '~/.sonar'
    restoreKeys: |
      sonar | $(Agent.OS)
  displayName: 'Cache SonarQube packages'

- script: |
    mvn verify sonar:sonar -Dsonar.projectKey=$(SONAR_PROJECTKEY) -Dsonar.projectName=$(SONAR_PROJECTNAME)
  displayName: 'Run SonarQube Analysis'
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)
    SONAR_HOST_URL: $(SONAR_HOST_URL)
