trigger:
  - master # or the name of your main branch

steps:
  # Checkout the repository
  - checkout: self

  # Disable shallow fetch
  - script: echo "Disabling shallow fetch..."
    displayName: 'Disable shallow fetch'
    env:
      GIT_DEPTH: 0

  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: ''
      scannerMode: 'Other'
      extraProperties: |
        sonar.projectKey="not-azure"
        sonar.host.url=$(SONAR_HOST_URL)
        sonar.login=$(SONAR_TOKEN)

  # Publish Quality Gate Result task
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'
