trigger:
  branches:
    include:
      - master  # or the name of your main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate VM image

steps:
  # Checkout the repository
  - checkout: self

  # Disable shallow fetch
  - script: echo "Disabling shallow fetch..."
    displayName: 'Disable shallow fetch'
    env:
      GIT_DEPTH: 0

  # Install JDK
  - task: JavaToolInstaller@1
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
      jdkSource: 'PreInstalled'

  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'main_server'
      scannerMode: 'Other'
      configMode: 'manual'
      additionalProperties: |
        sonar.projectKey=not-azure
        sonar.projectName=not-azure

  # Run SonarQube analysis
  - script: ./gradlew sonarqube
    displayName: 'Run SonarQube Analysis'

  # Publish SonarQube Quality Gate Result
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'
