trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- checkout: self
  displayName: 'Checkout Source'

- script: |
    echo $(SONAR_HOST_URL)
    sleep 10
    docker pull blacklocksec/code-scanner:latest
    docker run --rm -v $(Build.SourcesDirectory):/app \
      -e SONAR_PROJECTKEY=hi-tester \
      -e SONAR_HOST_URL=$(SONAR_HOST_URL) \
      -e SONAR_TOKEN=$(SONAR_TOKEN) \
      blacklocksec/code-scanner:latest
  displayName: 'Run Blacklock Code Scanner'
  env:
    SONAR_HOST_URL: $(SONAR_HOST_URL)
    SONAR_TOKEN: $(SONAR_TOKEN)
