trigger:
  branches:
    include:
      - master # or the name of your main branch

steps:
  # Checkout the repository
  - checkout: self

  # Disable shallow fetch
  - script: echo "Disabling shallow fetch..."
    displayName: 'Disable shallow fetch'
    env:
      GIT_DEPTH: 0

  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'main_server'
      scannerMode: 'Other'

  # Run SonarQube analysis
  - task: SonarQubeAnalyze@6
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
