trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONAR_PROJECTKEY: 'azure-the-test'
  SONAR_PROJECTNAME: 'azure-the-test'

steps:
- checkout: self
  displayName: 'Checkout Source'

- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    java -version
    mvn -version
  displayName: 'Install JDK 17 and Maven'

- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-17-jdk
    java -version
    mvn -version
    mvn verify sonar:sonar -Dsonar.projectKey=$(SONAR_PROJECTKEY) -Dsonar.projectName=$(SONAR_PROJECTNAME)
  displayName: 'Run SonarQube Analysis'
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)
    SONAR_HOST_URL: $(SONAR_HOST_URL)
