trigger:
  branches:
    include:
      - master  # or the name of your main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate VM image

steps:
  # Checkout the repository
  - checkout: self

  # Disable shallow fetch
  - script: echo "Disabling shallow fetch..."
    displayName: 'Disable shallow fetch'
    env:
      GIT_DEPTH: 0

  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'main_server'
      scannerMode: 'Other'
      configMode: 'manual'
      additionalProperties: |
        sonar.projectKey=not-azure
        sonar.projectName=not-azure

  - task: SonarQubeAnalyze@6
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
  - script: mvn clean install sonar:sonar
    displayName: 'Build with Maven and run SonarQube Analysis'
    env:
      MAVEN_OPTS: '-Xmx1024m'

  # Publish SonarQube Quality Gate Result
  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'
